export class Pending {
    applicant_id?:Number;
    tenant_id?:Number;
    property_id?:Number;
    full_name?:String;
    last_name?:String;
    email?:String;
    phone_num?:String;
    age?:Number;
    id_doc?:Text;
    occupation?:String;
    view_date?:Date;
    num_tenants?:Number;
    num_pets?:Number;
    ped_desc?:Text;
    smoke?:CharacterData;
    app_create_time?:Date;
    p_address?: String;
    p_city?: String;
    p_town?:String;
    p_zip_code?:String;
    p_name?:String;
    paymentStart: any;
    agreementStart: any;
    paymentEnd: any;
    agreementEnd: any;
    unit: any;
    amount: any;
    PaymentType: any;
}
